version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8.1
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - JUTE_MAXBUFFER=4194304 # Increase buffer size to 4MB
    networks:
      - kafka-network

  kafka:
    image: bitnami/kafka:3.5.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"  # Change the kafka host port to 8081, keeping container port 8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - kafka-network

  singlestore:
    image: ghcr.io/singlestore-labs/singlestoredb-dev
    container_name: singlestoredb
    environment:
      - ROOT_PASSWORD=S2admin@2024
    ports:
      - "3306:3306"
      - "8082:8080"  # Change the singlestore host port to 8082, keeping container port 8080
      - "9000:9000"
    volumes:
      - "my_cool_volume:/data"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
volumes:
  my_cool_volume:
